import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const source=readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');
const copy=x=>JSON.parse(JSON.stringify(x));
function element(){return {value:'',checked:false,dataset:{},style:{},children:[],classList:{toggle(){},add(){},remove(){}},setAttribute(){},addEventListener(){},append(...v){this.children.push(...v)},replaceChildren(...v){this.children=v},querySelector(){return element()},querySelectorAll(){return []},close(){},showModal(){},remove(){}}}
function setup(saved=null){
 const nodes=new Map(),cards=[],store=new Map(saved===null?[]:[['erica-seat-planner:v1',saved]]),downloads=[];
 const get=s=>{if(!nodes.has(s))nodes.set(s,element());return nodes.get(s)};
 const ctx={crypto:{randomUUID:()=>`test-${Math.random()}`},setTimeout:()=>1,clearTimeout(){},Blob,window:{confirm:()=>true},document:{querySelector:get,querySelectorAll:s=>s.includes('reference-card')?cards:[],createElement:element,createElementNS:element},localStorage:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v)},FileReader:class{readAsText(file){this.result=file;this.onload()}}};
 vm.createContext(ctx);
 vm.runInContext(source.replace('  init();',`renderAll=()=>{};renderAutoDraft=()=>{};syncEventInputs=()=>{};downloadBlob=(blob,name)=>globalThis.downloads.push({blob,name});
 globalThis.a={defaultState,sanitizeState,validateStateDocument,scheduleSave,applyMode,importJson,calculateAutoDraft,applyAutoDraft,restore,assignAttendee,unassignAttendee,renderAttendees,exportCsv,parseCsv,normalizeBulkRows,validateBulkRows,registerBulkRows,roomTemplate,suggestedReferenceMap,
 get state(){return state},set state(v){state=v},get draft(){return autoDraft},get undo(){return undoStack},set bulk(v){bulkPreviewRows=v}};`),ctx);
 ctx.downloads=downloads;
 return {a:ctx.a,get,store,downloads,ctx,refs(refs){cards.splice(0,cards.length,...Object.entries(refs).map(([id,value])=>({dataset:{institutionId:id},querySelector:()=>({value})})))}};
}
const person=(id,group='A',rank=1,extra={})=>({id,name:`가상-${id}`,org:'가상기관',title:'',type:'외부',group,note:'',institutionId:group,institutionRank:rank,fixedSeatId:'',seatLocked:false,...extra});
const institution=(id,i=1)=>({id,name:id,role:'other',displayOrder:i,referenceSeatId:'',note:''});
function scenario(people,assignments={},refs={A:'MAIN-L-12'},groups=[institution('A')]){const h=setup();h.a.state=h.a.sanitizeState({...h.a.defaultState(),attendees:people,institutions:groups,assignments});h.refs(refs);h.get('#auto-fill-staff').checked=true;return h}
test('Geometry remains 63 seats / 49 monitors / 7 staff modules / aligned center',()=>{const t=setup().a.roomTemplate;assert.equal(t.seats.length,63);assert.equal(new Set(t.seats.map(s=>s.id)).size,63);assert.equal(t.seats.filter(s=>s.section!=='staff').length,49);assert.equal(t.geometry.staffTables.length,7);assert.equal(t.seats.find(s=>s.id==='HEAD-01').y,t.geometry.screen.y+t.geometry.screen.height/2)});
test('main furniture maps 2 seats to each of 12 upper and 12 lower modules while HEAD uses the integrated left leg',()=>{const t=setup().a.roomTemplate;const modules=t.geometry.mainTable.modules;assert.equal(modules.length,24);assert.equal(modules.filter(m=>m.section==='main-left').length,12);assert.equal(modules.filter(m=>m.section==='main-right').length,12);assert.deepEqual(copy(modules[0].seatIds),['MAIN-L-01','MAIN-L-02']);assert.deepEqual(copy(modules[11].seatIds),['MAIN-L-23','MAIN-L-24']);assert.deepEqual(copy(modules[12].seatIds),['MAIN-R-01','MAIN-R-02']);assert.deepEqual(copy(modules[23].seatIds),['MAIN-R-23','MAIN-R-24']);assert.deepEqual(copy(t.geometry.headTable.seatIds),['HEAD-01']);assert.equal(t.geometry.headTable.integratedWith,'main-table');assert.equal(t.geometry.headTable.structure,'left-vertical-leg');assert.equal(t.geometry.headTable.tableCount,1)});
test('legacy long text is not silently shortened on reload',()=>{const h=setup();const incoming={...h.a.defaultState(),attendees:[person('a','',null,{name:'가'.repeat(100),org:'나'.repeat(150)})]};h.a.validateStateDocument(incoming);assert.equal(h.a.sanitizeState(incoming).attendees[0].name.length,100);assert.equal(h.a.sanitizeState(incoming).attendees[0].org.length,150)});
for(const raw of ['{broken',JSON.stringify({schemaVersion:99,attendees:[],assignments:{}})])test('invalid stored original is not overwritten: '+raw.slice(0,12),()=>{const h=setup(raw);h.a.applyMode();assert.equal(h.store.get('erica-seat-planner:v1'),raw)});
test('valid V1 loads without institutions',()=>{const h=setup(JSON.stringify({schemaVersion:1,attendees:[person('a','',null)],assignments:{'HEAD-01':'a'}}));assert.equal(h.a.state.attendees.length,1);assert.equal(h.a.state.assignments['HEAD-01'],'a')});
test('invalid JSON import is atomic',()=>{const h=scenario([person('a')]);const before=JSON.stringify(h.a.state);for(const invalid of [{schemaVersion:99,attendees:[],assignments:{}},{schemaVersion:1,attendees:[],assignments:null},{schemaVersion:1,attendees:[person('a'),person('a')],assignments:{}},{schemaVersion:1,attendees:[],assignments:{},event:{title:{bad:true}}}]){h.a.importJson(JSON.stringify(invalid));assert.equal(JSON.stringify(h.a.state),before)}});
test('JSON import cancellation preserves all state; successful replace backs up and undoes',()=>{const h=scenario([person('a')]);h.a.scheduleSave();const before=JSON.stringify(h.a.state);const incoming=JSON.stringify({...h.a.defaultState(),attendees:[person('b')]});h.ctx.window.confirm=()=>false;h.a.importJson(incoming);assert.equal(JSON.stringify(h.a.state),before);h.ctx.window.confirm=()=>true;h.a.importJson(incoming);assert.equal(h.store.get('erica-seat-planner:v1:before-replace'),before);h.a.restore(h.a.undo.pop());assert.equal(JSON.stringify(h.a.state),before)});
test('cross-tab stale write cannot replace current storage',()=>{const h=scenario([person('a')]);h.a.scheduleSave();h.store.set('erica-seat-planner:v1','external-newer');h.a.assignAttendee('a','MAIN-L-01');assert.equal(h.store.get('erica-seat-planner:v1'),'external-newer');assert.deepEqual(copy(h.a.state.assignments),{})});
test('untrusted attendee ID is escaped at HTML sink',()=>{const h=scenario([person('"><img src=x onerror=alert(1)>')]);h.a.renderAttendees();const html=h.get('#attendee-list').children[0].innerHTML;assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img'))});
test('locked attendee cannot be moved, displaced or unassigned',()=>{const h=scenario([person('a','A',1,{seatLocked:true,fixedSeatId:'MAIN-L-12'}),person('b')],{'MAIN-L-12':'a'});h.a.assignAttendee('b','MAIN-L-12');h.a.assignAttendee('a','MAIN-L-13');h.a.unassignAttendee('a');assert.deepEqual(copy(h.a.state.assignments),{'MAIN-L-12':'a'})});
test('ordinary swap persists and undo restores',()=>{const h=scenario([person('a'),person('b')],{'MAIN-L-01':'a','MAIN-R-01':'b'});const before=copy(h.a.state);h.a.assignAttendee('a','MAIN-R-01');assert.equal(h.a.state.assignments['MAIN-L-01'],'b');assert.equal(JSON.parse(h.store.get('erica-seat-planner:v1')).assignments['MAIN-R-01'],'a');h.a.restore(h.a.undo.pop());assert.deepEqual(copy(h.a.state),before)});
test('fixed leader at reference permits next ranked person nearby',()=>{const h=scenario([person('a','A',1,{seatLocked:true,fixedSeatId:'MAIN-L-12'}),person('b','A',2)],{'MAIN-L-12':'a'});h.a.calculateAutoDraft();assert.equal(h.a.draft.errors.length,0);assert.equal(h.a.draft.assignments['MAIN-L-11'],'b')});
test('all institutions references are reserved before expansion',()=>{const h=scenario([person('a1'),person('a2','A',2),person('a3','A',3),person('b','B',1)],{}, {A:'MAIN-L-12',B:'MAIN-L-13'},[institution('A'),institution('B',2)]);h.a.calculateAutoDraft();assert.equal(h.a.draft.errors.length,0);assert.equal(h.a.draft.assignments['MAIN-L-13'],'b')});
test('manual staff and HEAD survive default fill and explicit recalc keeps HEAD',()=>{const h=scenario([person('a'),person('s','',null,{type:'수행원'})],{'HEAD-01':'a','STAFF-14':'s'});h.a.calculateAutoDraft();assert.equal(h.a.draft.assignments['STAFF-14'],'s');assert.equal(h.a.draft.assignments['HEAD-01'],'a');h.get('#auto-replace-existing').checked=true;h.a.calculateAutoDraft();assert.equal(h.a.draft.assignments['HEAD-01'],'a')});
test('HEAD requires explicit attendee selection',()=>{const h=scenario([person('a','',null)],{}, {},[]);h.get('#auto-include-head').checked=true;h.a.calculateAutoDraft();assert.ok(h.a.draft.errors.length);h.get('#auto-head-attendee').value='a';h.a.calculateAutoDraft();assert.equal(h.a.draft.errors.length,0);assert.equal(h.a.draft.assignments['HEAD-01'],'a')});
test('insufficient capacity blocks apply and preserves prior state',()=>{const h=scenario(Array.from({length:25},(_,i)=>person(`p${i}`,'A',i+1)));const before=copy(h.a.state);h.a.calculateAutoDraft();assert.ok(h.a.draft.errors.length);h.a.applyAutoDraft();assert.deepEqual(copy(h.a.state),before)});
test('preview, cancel without apply, apply/undo and stale preview protection',()=>{const h=scenario([person('a'),person('b','A',2)]);const before=copy(h.a.state);h.a.calculateAutoDraft();assert.deepEqual(copy(h.a.state),before);h.a.applyAutoDraft();assert.equal(Object.keys(h.a.state.assignments).length,2);h.a.restore(h.a.undo.pop());assert.deepEqual(copy(h.a.state),before);h.a.calculateAutoDraft();h.a.state.event.note='new note';h.a.applyAutoDraft();assert.equal(Object.keys(h.a.state.assignments).length,0)});
for(const count of [1,2,3,6,10])test(`${count} institutions, mixed roles, no duplicate allocation`,()=>{const groups=Array.from({length:count},(_,i)=>({...institution(`I${i}`,i+1),role:i%3===0?'host':'counterparty'}));const h=scenario(groups.flatMap(g=>[1,2,3].map(rank=>person(`${g.id}-${rank}`,g.id,rank))),{},Object.fromEntries(setup().a.suggestedReferenceMap(groups)),groups);h.a.calculateAutoDraft();assert.equal(h.a.draft.errors.length,0);assert.equal(Object.keys(h.a.draft.assignments).length,count*3);assert.equal(new Set(Object.values(h.a.draft.assignments)).size,count*3)});
for(const side of ['L','R'])for(const pivot of [1,12,24])test(`coordinate expansion ${side}-${pivot} odd/even`,()=>{for(const n of [3,4]){const h=scenario(Array.from({length:n},(_,i)=>person(`p${i}`,'A',i+1)),{}, {A:`MAIN-${side}-${String(pivot).padStart(2,'0')}`});h.a.calculateAutoDraft();assert.equal(h.a.draft.errors.length,0);assert.equal(Object.keys(h.a.draft.assignments).length,n)}});
test('CSV rejects malformed quotes and exports ordinary assignments with safe formula text',async()=>{const h=scenario([person('a','A',1,{name:'=1+1'})],{'MAIN-L-03':'a'});assert.throws(()=>h.a.parseCsv('이름\na,"broken'));h.a.exportCsv();const csv=await h.downloads[0].blob.text();assert.ok(csv.includes('배정좌석'));assert.ok(csv.includes('MAIN-L-03'));assert.ok(csv.includes("'=1+1"));const rows=h.a.normalizeBulkRows(h.a.parseCsv(csv));assert.equal(rows[0].assignedSeat,'MAIN-L-03');assert.equal(rows[0].fixedSeat,'')});
